#!/bin/bash
#
# Lock the screen.
# 
# Application to be manually invoked by the user.
#
# Assumes that ./boot was run at boot time.

set -e

SCRIPT_NAME="${BASH_SOURCE[0]##*/}"
SCRIPT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
source "$SCRIPT_DIR/common"

sudo rm -f "/tmp/unlock" #just for the xterm example, should generally not be needed

sudo chvt $LOCK_VT
physlock -l
